In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten

In [2]:
def prepare_data(timeseries_data, n_features):
	X, y =[],[]
	for i in range(len(timeseries_data)):
		# find the end of this pattern
		end_ix = i + n_features
		# check if we are beyond the sequence
		if end_ix > len(timeseries_data)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = timeseries_data[i:end_ix], timeseries_data[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [12]:
import pandas as pd
import os as os
os.chdir(r'C:\Users\Sharath Chandra\Desktop\Palmoil_Dashboard_FinalApp_FinalReport\Palmoil_Dashboard_FinalApp')
timeseries_data= pd.read_csv('Boerno_RawData.csv')
timeseries_data=timeseries_data['CLOSING STOCK OF CPO (Ton)']

In [13]:
# define input sequence
# timeseries_data = [110, 125, 133, 146, 158, 172, 187, 196, 210]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = prepare_data(timeseries_data, n_steps)

In [20]:
n_features = 1
x_input = X.reshape((X.shape[0], X.shape[1], n_features))
# X

In [21]:
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=300, verbose=1)

Epoch 1/300
3/3 [==============================] - 8s 8ms/step - loss: 1536865370112.0000
Epoch 2/300
3/3 [==============================] - 0s 5ms/step - loss: 1495656726528.0000
Epoch 3/300
3/3 [==============================] - 0s 4ms/step - loss: 1359160410112.0000
Epoch 4/300
3/3 [==============================] - 0s 8ms/step - loss: 1354937597952.0000
Epoch 5/300
3/3 [==============================] - 0s 5ms/step - loss: 1311785910272.0000
Epoch 6/300
3/3 [==============================] - 0s 7ms/step - loss: 1425994416128.0000
Epoch 7/300
3/3 [==============================] - 0s 6ms/step - loss: 1361750720512.0000
Epoch 8/300
3/3 [==============================] - 0s 6ms/step - loss: 1398812114944.0000
Epoch 9/300
3/3 [==============================] - 0s 9ms/step - loss: 1346917531648.0000
Epoch 10/300
3/3 [==============================] - 0s 11ms/step - loss: 1338622410752.0000
Epoch 11/300
3/3 [==============================] - 0s 5ms/step - loss: 1321192947712.0000
Epoch 1

3/3 [==============================] - 0s 5ms/step - loss: 39952727040.0000
Epoch 93/300
3/3 [==============================] - 0s 9ms/step - loss: 46720320512.0000
Epoch 94/300
3/3 [==============================] - 0s 5ms/step - loss: 49685506048.0000
Epoch 95/300
3/3 [==============================] - 0s 5ms/step - loss: 42097680384.0000
Epoch 96/300
3/3 [==============================] - 0s 6ms/step - loss: 41641196544.0000
Epoch 97/300
3/3 [==============================] - 0s 6ms/step - loss: 44221557760.0000
Epoch 98/300
3/3 [==============================] - 0s 6ms/step - loss: 41432184832.0000
Epoch 99/300
3/3 [==============================] - 0s 7ms/step - loss: 45163711488.0000
Epoch 100/300
3/3 [==============================] - 0s 6ms/step - loss: 43364775936.0000
Epoch 101/300
3/3 [==============================] - 0s 5ms/step - loss: 53953394688.0000
Epoch 102/300
3/3 [==============================] - 0s 5ms/step - loss: 62641557504.0000
Epoch 103/300
3/3 [============

3/3 [==============================] - 0s 5ms/step - loss: 42433934336.0000
Epoch 184/300
3/3 [==============================] - 0s 2ms/step - loss: 41158493184.0000
Epoch 185/300
3/3 [==============================] - 0s 2ms/step - loss: 43949011968.0000
Epoch 186/300
3/3 [==============================] - 0s 6ms/step - loss: 42357831680.0000
Epoch 187/300
3/3 [==============================] - 0s 6ms/step - loss: 39244211200.0000
Epoch 188/300
3/3 [==============================] - 0s 4ms/step - loss: 43124888576.0000
Epoch 189/300
3/3 [==============================] - 0s 7ms/step - loss: 41067244544.0000
Epoch 190/300
3/3 [==============================] - 0s 5ms/step - loss: 44285522944.0000
Epoch 191/300
3/3 [==============================] - 0s 4ms/step - loss: 39378989568.0000
Epoch 192/300
3/3 [==============================] - 0s 6ms/step - loss: 41691115520.0000
Epoch 193/300
3/3 [==============================] - 0s 6ms/step - loss: 43905452032.0000
Epoch 194/300
3/3 [=====

3/3 [==============================] - 0s 2ms/step - loss: 43590234112.0000
Epoch 275/300
3/3 [==============================] - 0s 5ms/step - loss: 44110455808.0000
Epoch 276/300
3/3 [==============================] - 0s 5ms/step - loss: 44176290816.0000
Epoch 277/300
3/3 [==============================] - 0s 8ms/step - loss: 39957838848.0000
Epoch 278/300
3/3 [==============================] - 0s 8ms/step - loss: 46124801024.0000
Epoch 279/300
3/3 [==============================] - 0s 5ms/step - loss: 41201860608.0000
Epoch 280/300
3/3 [==============================] - 0s 3ms/step - loss: 40743313408.0000
Epoch 281/300
3/3 [==============================] - 0s 8ms/step - loss: 40770168832.0000
Epoch 282/300
3/3 [==============================] - 0s 8ms/step - loss: 41409497088.0000
Epoch 283/300
3/3 [==============================] - 0s 7ms/step - loss: 45798682624.0000
Epoch 284/300
3/3 [==============================] - 0s 5ms/step - loss: 46155210752.0000
Epoch 285/300
3/3 [=====

In [23]:
# demonstrate prediction for next 10 days
import numpy as np
# x_input = np.array([187, 196, 210])
n_features = 1
x_input = X.reshape((X.shape[0], X.shape[1], n_features))
temp_input=list(x_input)
lst_output=[]
i=0
while(i<10):
    
    if(len(temp_input)>3):
        x_input=np.array(temp_input[1:])
        print("{} day input {}".format(i,x_input))
        #print(x_input)
        x_input = x_input.reshape((1, n_steps, n_features))
        #print(x_input)
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input=temp_input[1:]
        #print(temp_input)
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
    

print(lst_output)

0 day input [[[ 923011]
  [ 866087]
  [1003714]]

 [[ 866087]
  [1003714]
  [ 979793]]

 [[1003714]
  [ 979793]
  [ 828434]]

 [[ 979793]
  [ 828434]
  [ 895376]]

 [[ 828434]
  [ 895376]
  [1133477]]

 [[ 895376]
  [1133477]
  [1178596]]

 [[1133477]
  [1178596]
  [1195355]]

 [[1178596]
  [1195355]
  [1303956]]

 [[1195355]
  [1303956]
  [ 995691]]

 [[1303956]
  [ 995691]
  [ 878201]]

 [[ 995691]
  [ 878201]
  [ 949046]]

 [[ 878201]
  [ 949046]
  [ 905330]]

 [[ 949046]
  [ 905330]
  [1269971]]

 [[ 905330]
  [1269971]
  [1286779]]

 [[1269971]
  [1286779]
  [1098345]]

 [[1286779]
  [1098345]
  [1254086]]

 [[1098345]
  [1254086]
  [1462197]]

 [[1254086]
  [1462197]
  [1568155]]

 [[1462197]
  [1568155]
  [1707383]]

 [[1568155]
  [1707383]
  [1753226]]

 [[1707383]
  [1753226]
  [1593073]]

 [[1753226]
  [1593073]
  [1302000]]

 [[1593073]
  [1302000]
  [1251919]]

 [[1302000]
  [1251919]
  [ 955412]]

 [[1251919]
  [ 955412]
  [ 973815]]

 [[ 955412]
  [ 973815]
  [ 883175]]



ValueError: cannot reshape array of size 243 into shape (1,3,1)